### ISSUE TITLE
CLI doesn't work

### ISSUE THREAD

**Issue by subdan** [soimy/msdf-bmfont-xml#5]
I get this error:

```
$ msdf-bmfont
env: node\r: No such file or directory
```

**Comment by subdan** [comment]
Executable file from bin folder also doesn't work
`msdfgen.osx msdf -font Arial.ttf `

```
Unknown setting or insufficient parameters: -font
Unknown setting or insufficient parameters: Arial.ttf
Use -help for more information.
No input specified! Use either -svg <file.svg> or -font <file.ttf/otf> <character code>, or see -help.
```

**Comment by soimy** [comment]
@subdan can you confirm node.js executable is in your path? Just type `node -v` to confirm it.
`msdfgen.osx` is not the executable you want.

**Comment by subdan** [comment]
```
$ node -v
v8.4.0
```

**Comment by soimy** [comment]
@subdan Thanks for the reporting, it seems an issue npm/npm#12371 and the recent version is published via windows. I'm fixing now

**Comment by subdan** [comment]
Windows version of your CLI also doesn't work.
![screen shot 2017-08-26 at 17 12 48](https://user-images.githubusercontent.com/410293/29742111-dd7c2702-8a81-11e7-816d-8d8e3b9e9230.png)

**Comment by subdan** [comment]
![screen shot 2017-08-26 at 17 14 12](https://user-images.githubusercontent.com/410293/29742120-035817b0-8a82-11e7-94c6-d743afafcc90.png)

**Comment by soimy** [comment]
@subdan can you try re-install it? From your log it seems one of the core dependencies `node-canvas-prebuilt` download failed with a 404.

**Comment by subdan** [comment]
Yes, I can but in an 1-2 hours.

**Comment by soimy** [comment]
OSX `env: node\r: No such file or directory` issue should be fixed in f151c1958ff7520473c93f034fe1ae51979e0734
And now bump to new version `2.2.3` with new option `--tolerance`
Try update it via `npm update -g msdf-bmfont-xml`

**Comment by soimy** [comment]
@subdan Just noticed that there is no `node-canvas-prebuilt` support for arch `ia32`, only `x64`. If you only have 32bit windows, you should manually install `node-canvas` instead. Here is how:
install [pre-requirement for windows ](https://github.com/Automattic/node-canvas/wiki/Installation---Windows), then:
```bash
git clone https://github.com/soimy/msdf-bmfont-xml.git
npm install canvas
```
in file `index.js` replace `const canvas = require('canvas-prebuilt')` to `const canvas = require('canvas')`
```bash
npm link
```

**Comment by subdan** [comment]
Win: Re-install didn't help. I still get 404 error.
macOS: Now it works!

**Comment by soimy** [comment]
I'm closing this issue after finding out `canvas-prebuilt` will not support `win32-ia32` arch
